-- MySQL Script generated by MySQL Workbench
-- Tue May  9 11:34:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sbassess
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sbassess` ;

-- -----------------------------------------------------
-- Schema sbassess
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sbassess` DEFAULT CHARACTER SET utf8 ;
USE `sbassess` ;

-- -----------------------------------------------------
-- Table `sbassess`.`TodoList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sbassess`.`TodoList` ;

CREATE TABLE IF NOT EXISTS `sbassess`.`TodoList` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `targetDate` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
