-- MySQL Script generated by MySQL Workbench
-- Thu May  4 16:21:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Shop` ;

-- -----------------------------------------------------
-- Schema Shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Shop` DEFAULT CHARACTER SET utf8 ;
USE `Shop` ;

-- -----------------------------------------------------
-- Table `Shop`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shop`.`Customer` ;

CREATE TABLE IF NOT EXISTS `Shop`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `mobile` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
