-- MySQL Script generated by MySQL Workbench
-- Tue May  2 16:00:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema itemsdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `itemsdb` ;

-- -----------------------------------------------------
-- Schema itemsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itemsdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `itemsdb` ;

-- -----------------------------------------------------
-- Table `itemsdb`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itemsdb`.`Item` ;

CREATE TABLE IF NOT EXISTS `itemsdb`.`Item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `imageUrl` VARCHAR(200) NOT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `style` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
